package cn.flyme.shop.mapper;

import cn.flyme.shop.entities.Cata;
import cn.flyme.shop.entities.CataExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Component
public interface CataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cata
     *
     * @mbg.generated Sun Jul 14 16:11:04 CST 2019
     */
    long countByExample(CataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cata
     *
     * @mbg.generated Sun Jul 14 16:11:04 CST 2019
     */
    int deleteByExample(CataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cata
     *
     * @mbg.generated Sun Jul 14 16:11:04 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cata
     *
     * @mbg.generated Sun Jul 14 16:11:04 CST 2019
     */
    int insert(Cata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cata
     *
     * @mbg.generated Sun Jul 14 16:11:04 CST 2019
     */
    int insertSelective(Cata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cata
     *
     * @mbg.generated Sun Jul 14 16:11:04 CST 2019
     */
    List<Cata> selectByExample(CataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cata
     *
     * @mbg.generated Sun Jul 14 16:11:04 CST 2019
     */
    Cata selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cata
     *
     * @mbg.generated Sun Jul 14 16:11:04 CST 2019
     */
    int updateByExampleSelective(@Param("record") Cata record, @Param("example") CataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cata
     *
     * @mbg.generated Sun Jul 14 16:11:04 CST 2019
     */
    int updateByExample(@Param("record") Cata record, @Param("example") CataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cata
     *
     * @mbg.generated Sun Jul 14 16:11:04 CST 2019
     */
    int updateByPrimaryKeySelective(Cata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cata
     *
     * @mbg.generated Sun Jul 14 16:11:04 CST 2019
     */
    int updateByPrimaryKey(Cata record);
}