package cn.flyme.shop.mapper;

import cn.flyme.shop.entities.Statistics;
import cn.flyme.shop.entities.StatisticsExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Component
public interface StatisticsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statistics
     *
     * @mbg.generated Sun Jul 14 16:11:04 CST 2019
     */
    long countByExample(StatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statistics
     *
     * @mbg.generated Sun Jul 14 16:11:04 CST 2019
     */
    int deleteByExample(StatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statistics
     *
     * @mbg.generated Sun Jul 14 16:11:04 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statistics
     *
     * @mbg.generated Sun Jul 14 16:11:04 CST 2019
     */
    int insert(Statistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statistics
     *
     * @mbg.generated Sun Jul 14 16:11:04 CST 2019
     */
    int insertSelective(Statistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statistics
     *
     * @mbg.generated Sun Jul 14 16:11:04 CST 2019
     */
    List<Statistics> selectByExample(StatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statistics
     *
     * @mbg.generated Sun Jul 14 16:11:04 CST 2019
     */
    Statistics selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statistics
     *
     * @mbg.generated Sun Jul 14 16:11:04 CST 2019
     */
    int updateByExampleSelective(@Param("record") Statistics record, @Param("example") StatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statistics
     *
     * @mbg.generated Sun Jul 14 16:11:04 CST 2019
     */
    int updateByExample(@Param("record") Statistics record, @Param("example") StatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statistics
     *
     * @mbg.generated Sun Jul 14 16:11:04 CST 2019
     */
    int updateByPrimaryKeySelective(Statistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statistics
     *
     * @mbg.generated Sun Jul 14 16:11:04 CST 2019
     */
    int updateByPrimaryKey(Statistics record);
}